name: "Github Actions Pragmatic Programmer Bot"

on:
  push:
  schedule:
    - cron: '0 07 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@v1
      -name: 'Install node'
      uses: actions/setup-node@v1
      -name: 'Install NPM dependencies'
      run: npm Install
      -name: 'Runb code'
      run: node index.js
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID  }}
